### ISSUE TITLE
Updates first viewed NFO successfully then traps and subsequently fails to update .NFO files

### ISSUE THREAD

**Issue by dbareis** [4lb3rtO/service.nfo.watchedstate.updater#5]
This is on KODI 17.6 on Android 7.1.1.

This is the part of the log for the successfully updated .NFO (first watched movie):

> 15:14:04.680 T:18446744073012246832   DEBUG: DoWork - Saving file state for video item smb://192.168.1.99/multi-media/TvShows/#Science Fiction and Fantasy/Angel/Season 1/Angel - s01e01 - City of.avi
> 15:14:04.687 T:18446744072944875824   DEBUG: DoWork - took 122 ms to load special://masterprofile/Thumbnails/0/0c1a40cd.jpg
> 15:14:04.695 T:18446744073012246832   DEBUG: DoWork - Marking video item smb://192.168.1.99/multi-media/TvShows/#Science Fiction and Fantasy/Angel/Season 1/Angel - s01e01 - City of.avi as watched
> 15:14:04.710 T:18446744073429092656   DEBUG: CAnnouncementManager - Announcement: OnUpdate from xbmc
> 15:14:04.710 T:18446744073429092656   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnUpdate
> 15:14:04.931 T:18446744073429092656   DEBUG: CAnnouncementManager - Announcement: OnUpdate from xbmc
> 15:14:04.931 T:18446744073429092656   DEBUG: GOT ANNOUNCEMENT, type: 16, from xbmc, message OnUpdate
> 15:14:04.933 T:18446744073060481328   DEBUG: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"VideoLibrary.GetEpisodeDetails","params":{"episodeid":3309,"properties":["file"]},"id":1}
> 15:14:04.999 T:18446744073060481328   DEBUG: CSMBFile::Open - opened smb://192.168.1.99/multi-media/TvShows/#Science Fiction and Fantasy/Angel/Season 1/Angel - s01e01 - City of.nfo, fd=10003
> 15:14:05.010 T:18446744073068091696   DEBUG: JSONRPC: Incoming request: {"jsonrpc": "2.0", "method": "VideoLibrary.GetTVShows", "params": {"properties": ["title", "studio", "mpaa", "file", "art"], "sort": {"order": "descending", "method": "lastplayed"}, "filter": {"field": "inprogress", "operator": "true", "value": ""}, "limits": {"end": 20}}, "id": 1}
> 15:14:05.031 T:18446744073060481328   DEBUG: CSMBFile::Close closing fd 10003
> 15:14:05.084 T:18446744073060481328 WARNING: SMBFile::OpenForWrite() called with overwriting enabled! - smb://USERNAME:PASSWORD@192.168.1.99/multi-media/TvShows/%23Science%20Fiction%20and%20Fantasy/Angel/Season%201/Angel%20-%20s01e01%20-%20City%20of.nfo
> 15:14:05.117 T:18446744073060481328   DEBUG: CSMBFile::Close closing fd 10003

> 15:14:05.128 T:18446744073068091696   DEBUG: RunQuery took 99 ms for 51 items query: SELECT * FROM tvshow_view  WHERE ( ((tvshow_view.watchedcount > 0 AND tvshow_view.watchedcount < tvshow_view.totalCount) OR (tvshow_view.watchedcount = 0 AND EXISTS (SELECT 1 FROM episode_view WHERE episode_view.idShow = tvshow_view.idShow AND episode_view.resumeTimeInSeconds > 0))))

> 15:14:05.138 T:18446744073060481328   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.KeyError'>
>                                             Error Contents: ('item',)
>                                             Traceback (most recent call last):
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.nfo.watchedstate.updater/default.py", line 118, in <module>
>                                                 WU.listen()
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.nfo.watchedstate.updater/default.py", line 51, in listen
>                                                 self.handleMsg(msg)
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.nfo.watchedstate.updater/default.py", line 37, in handleMsg
>                                                 methodHandler(jsonmsg)
>                                               File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.nfo.watchedstate.updater/default.py", line 55, in VideoLibraryOnUpdate
>                                                 if (jsonmsg["params"]["data"]["item"].has_key("id")) and (jsonmsg["params"]["data"]["item"].has_key("type")) and (jsonmsg["params"]["data"].has_key("playcount")):
>                                             KeyError: ('item',)
>                                             -->End of Python script error report<--
> 15:14:05.251 T:18446744073060481328    INFO: Python script stopped
>

**Comment by dbareis** [comment]
It looks like this has been abandoned, this works for me: 

https://kodi-addons.club/addon/service.nfo.watchedstate.updater_axbmcuser/1.1.12


[UPDATE] That site seems to be dead, I'm attaching the files.

[service.nfo.watchedstate.updater_axbmcuser-1.1.12.zip](https://github.com/4lb3rtO/service.nfo.watchedstate.updater/files/4424389/service.nfo.watchedstate.updater_axbmcuser-1.1.12.zip)

**Comment by droopified** [comment]
@dbareis thank you for the link to the updated fork! this addon is a must and was killing me so glad u linked a working version!

**Comment by dbareis** [comment]
This website seems to have a new version that I haven't tried (v1.2.0): 

https://kodi-addons.club/addon/service.nfo.watchedstate.updater/

**Comment by automobilly** [comment]
@dbareis
I know this thread is a bit older. For me this addon is also irreplaceable and important. I will try it tonight if it works with your changes. I would be very happy about that.
Since the last update in Kodi, this addon is marked as broken and there is no one to maintain it anymore.
Thanks for your work

**Comment by dbareis** [comment]
@automobilly not my change and also doesn't work with v19 Kodi, I haven't had time to look for an update yet, please let us know if you find one 😀

**Comment by ALEXK4747** [comment]
any update for this addon on matrix 19.1?

**Comment by dbareis** [comment]
Maybe this works (haven't tried yet but recently uploaded): https://www.kodinerds.net/index.php/Thread/72246-methodDict-VideoLibrary-OnUpdate-funktioniert-seit-Update-auf-Kodi-19-nicht-mehr/?postID=634696#post634696

**Comment by cooljimy84** [comment]
Access denied. You are not authorized to view this page.

**Comment by Jumpy73** [comment]
Even after being registered on the kodinerds.net forum and downloaded the service.nfo.updater-1.0.0+matrix.zip file, the addon can't be installed because an error rises during the installation procedure.

Do anyone know where to download an updated version of this addon on kodi matrix?

**Comment by Jumpy73** [comment]
Even after being registered on the kodinerds.net forum and downloaded the service.nfo.updater-1.0.0+matrix.zip file, the addon can't be installed because an error rises during the installation procedure.

Do anyone know where to download an updated version of this addon on kodi matrix?

**Comment by droopified** [comment]
> Even after being registered on the kodinerds.net forum and downloaded the service.nfo.updater-1.0.0+matrix.zip file, the addon can't be installed because an error rises during the installation procedure.
> 
> Do anyone know where to download an updated version of this addon on kodi matrix?

i had no idea they did a mod for matrix! after translating the website, i saw they said something about it being on a repo. i couldnt find it exactly but i found it on the website. try searching for service.nfo.updater-1.0.3+matrix

it works but with errors. here is what it wrote in my .nfo file...
<watched>true</watched><playcount>1</playcount></movie>ec> 

as you can see there is a weird out of place ec> at the end. but hey its something!
